using System.Net;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Logging.Abstractions;
using SmarterMailAgent.Auth;
using SmarterMailAgent.Profiles;
using SmarterMailAgent.Server;
using SmarterMailAgent.Storage;

namespace SmarterMailAgent.Tests;

public sealed class SealerTests
{
    [Fact]
    public void Round_trip_binds_label_and_context()
    {
        var sealer = new Sealer(RandomNumberGenerator.GetBytes(32));
        var sealedValue = sealer.SealString("secret"u8, "label-a", "p|1");

        Assert.Equal("secret", Encoding.UTF8.GetString(sealer.OpenString(sealedValue, "label-a", "p|1")!));
        Assert.Null(sealer.OpenString(sealedValue, "label-b", "p|1"));   // another use
        Assert.Null(sealer.OpenString(sealedValue, "label-a", "p|2"));   // another row
        Assert.Null(new Sealer(RandomNumberGenerator.GetBytes(32)).OpenString(sealedValue, "label-a", "p|1"));
    }

    [Fact]
    public void Previous_key_opens_but_never_seals()
    {
        var old = RandomNumberGenerator.GetBytes(32);
        var sealedOld = new Sealer(old).SealString("x"u8, "l");
        var rotated = new Sealer(RandomNumberGenerator.GetBytes(32), old);

        Assert.NotNull(rotated.OpenString(sealedOld, "l"));
        Assert.Null(new Sealer(old).OpenString(rotated.SealString("y"u8, "l"), "l"));
    }

    /// <summary>The remember-me bundle's wire format is unchanged by the move onto Sealer.</summary>
    [Fact]
    public void Empty_context_matches_the_original_resume_format()
    {
        var key = RandomNumberGenerator.GetBytes(32);
        var data = new Sealer(key).Seal("payload"u8, "sma-resume-v1");

        var label = Encoding.ASCII.GetBytes("sma-resume-v1");
        var aad = label.Concat(new[] { data[0], data[1] }).ToArray();
        var plaintext = new byte[data.Length - 2 - 12 - 16];
        using var aes = new AesGcm(key, 16);
        aes.Decrypt(data.AsSpan(2, 12), data.AsSpan(14, plaintext.Length), data.AsSpan(14 + plaintext.Length, 16), plaintext, aad);

        Assert.Equal(0x01, data[0]);
        Assert.Equal(SHA256.HashData(key)[0], data[1]);
        Assert.Equal("payload", Encoding.UTF8.GetString(plaintext));
    }
}

public sealed class ProfileCryptoTests
{
    [Fact]
    public void Transcript_seal_opens_only_with_the_private_key_and_context()
    {
        using var recipient = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
        var spki = Base64Url.Encode(recipient.ExportSubjectPublicKeyInfo());
        Assert.True(ProfileCrypto.IsValidPublicKey(spki));

        var sealedValue = ProfileCrypto.SealToPublicKey("hello report"u8, spki, "task-run|p|r");
        Assert.Equal("hello report", Encoding.UTF8.GetString(ProfileCrypto.OpenWithPrivateKey(sealedValue, recipient, "task-run|p|r")));

        Assert.ThrowsAny<CryptographicException>(() => ProfileCrypto.OpenWithPrivateKey(sealedValue, recipient, "task-run|p|other"));
        using var stranger = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
        Assert.ThrowsAny<CryptographicException>(() => ProfileCrypto.OpenWithPrivateKey(sealedValue, stranger, "task-run|p|r"));
    }

    /// <summary>
    /// The browser opens what the server seals: a vector checked in for the frontend's node tests
    /// (dev/test/vault.test.mjs). Regenerate with UPDATE_VECTORS=1.
    /// </summary>
    [Fact]
    public void Transcript_vector_for_the_browser()
    {
        var path = Path.Combine(RepoRoot(), "src", "Agent", "wwwroot", "dev", "test", "vectors", "transcript.json");
        if (Environment.GetEnvironmentVariable("UPDATE_VECTORS") == "1" || !File.Exists(path))
        {
            using var key = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
            const string context = "task-run|profile-123|run-456";
            const string plaintext = "{\"final\":\"Three unread messages, none urgent.\"}";
            var vector = new
            {
                note = "Generated by ProfileCryptoTests.Transcript_vector_for_the_browser; opened by vault.test.mjs.",
                privateKeyPkcs8 = Base64Url.Encode(key.ExportPkcs8PrivateKey()),
                publicKey = Base64Url.Encode(key.ExportSubjectPublicKeyInfo()),
                context,
                plaintext,
                sealedValue = ProfileCrypto.SealToPublicKey(Encoding.UTF8.GetBytes(plaintext), Base64Url.Encode(key.ExportSubjectPublicKeyInfo()), context),
            };
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, System.Text.Json.JsonSerializer.Serialize(vector, new System.Text.Json.JsonSerializerOptions { WriteIndented = true }) + "\n");
        }

        var json = System.Text.Json.JsonDocument.Parse(File.ReadAllText(path)).RootElement;
        using var recipient = ECDiffieHellman.Create();
        recipient.ImportPkcs8PrivateKey(Base64Url.Decode(json.GetProperty("privateKeyPkcs8").GetString())!, out _);
        var opened = ProfileCrypto.OpenWithPrivateKey(json.GetProperty("sealedValue").GetString()!, recipient,
            json.GetProperty("context").GetString()!);
        Assert.Equal(json.GetProperty("plaintext").GetString(), Encoding.UTF8.GetString(opened));
    }

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "SmarterMail.slnx")))
            dir = dir.Parent;
        return dir?.FullName ?? throw new InvalidOperationException("Repo root not found.");
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("not-base64!!")]
    [InlineData("AAAA")]
    public void Bad_public_keys_are_refused(string? spki) => Assert.False(ProfileCrypto.IsValidPublicKey(spki));

    [Fact]
    public void P384_keys_are_refused()
    {
        using var key = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP384);
        Assert.False(ProfileCrypto.IsValidPublicKey(Base64Url.Encode(key.ExportSubjectPublicKeyInfo())));
    }

    [Fact]
    public void Accounts_key_check_and_recovery_hash()
    {
        var key = RandomNumberGenerator.GetBytes(32);
        var check = ProfileCrypto.AccountsKeyCheck(key);
        Assert.True(ProfileCrypto.AccountsKeyMatches(key, check));
        Assert.False(ProfileCrypto.AccountsKeyMatches(RandomNumberGenerator.GetBytes(32), check));

        var auth = RandomNumberGenerator.GetBytes(32);
        var hash = ProfileCrypto.RecoveryAuthHash(auth);
        Assert.True(ProfileCrypto.RecoveryAuthMatches(auth, hash));
        Assert.False(ProfileCrypto.RecoveryAuthMatches(auth, null));
    }
}

public sealed class DataStoreTests
{
    private static ServerOptions Options(string dir) => new() { DataDir = dir };

    [Fact]
    public void Migrates_once_and_reopens()
    {
        var dir = TestEnvironment.NewDataDir();
        var first = new DataStore(Options(dir), NullLogger<DataStore>.Instance);
        var second = new DataStore(Options(dir), NullLogger<DataStore>.Instance);
        Assert.Equal(first.SchemaVersion, second.SchemaVersion);
        Assert.True(File.Exists(Path.Combine(dir, "smartermail-agent.db")));
    }

    [Fact]
    public void Unwritable_directory_fails_with_a_clear_message()
    {
        var file = Path.Combine(Path.GetTempPath(), $"sma-file-{Guid.NewGuid():N}");
        File.WriteAllText(file, "");
        var ex = Assert.Throws<InvalidOperationException>(() =>
            new DataStore(Options(Path.Combine(file, "sub")), NullLogger<DataStore>.Instance));
        Assert.Contains("BROWSER_ONLY_MODE", ex.Message);
    }

    [Fact]
    public void Profiles_passkeys_and_accounts()
    {
        var db = new DataStore(Options(TestEnvironment.NewDataDir()), NullLogger<DataStore>.Instance);
        var store = new ProfileStore(db);
        var now = DataStore.Now();

        store.CreateProfile(
            new ProfileRow("p1", now, now, "pub", "priv", null, 0, "check", null, null, null, false),
            new PasskeyRow("c1", "p1", [1, 2, 3], 0, null, "Laptop", "wrapped", now, null),
            [new StoredAccountRow("a1", "p1", ProfileStore.SealProfile, "ok", "blob", now)]);

        Assert.NotNull(store.GetProfile("p1"));
        Assert.Equal(1, store.CountProfiles());
        Assert.Equal("p1", store.GetPasskey("c1")!.ProfileId);

        // The last passkey cannot be deleted; a second one can.
        Assert.False(store.DeletePasskey("p1", "c1"));
        store.AddPasskey(new PasskeyRow("c2", "p1", [4], 0, null, null, "wrapped2", now, null));
        Assert.True(store.DeletePasskey("p1", "c1"));

        // Settings are optimistic.
        Assert.True(store.UpdateSettings("p1", "s1", 0, out var v1));
        Assert.False(store.UpdateSettings("p1", "s2", 0, out _));
        Assert.True(store.UpdateSettings("p1", "s2", v1, out _));

        // An upsert never moves a row to another profile.
        store.CreateProfile(
            new ProfileRow("p2", now, now, "pub", "priv", null, 0, "check", null, null, null, false),
            new PasskeyRow("c3", "p2", [5], 0, null, null, "w", now, null), []);
        store.UpsertAccount(new StoredAccountRow("a1", "p2", ProfileStore.SealProfile, "ok", "stolen", now));
        Assert.Equal("blob", store.Accounts("p1").Single().Blob);
        Assert.Empty(store.Accounts("p2"));

        store.DeleteProfile("p1");
        Assert.Null(store.GetPasskey("c2"));
        Assert.Empty(store.Accounts("p1"));
    }
}

/// <summary>One live owner per stored account, shared by sessions and tasks; locking forgets, never revokes.</summary>
public sealed class ProfileRuntimeTests
{
    private readonly StubSmarterMail _stub = new();
    private readonly ProfileStore _store;
    private readonly ProfileRegistry _registry;
    private readonly AccountRestorer _restorer;
    private readonly byte[] _accountsKey = RandomNumberGenerator.GetBytes(32);
    private readonly string _profileId = ProfileCrypto.NewId();

    public ProfileRuntimeTests()
    {
        var options = new ServerOptions { DataDir = TestEnvironment.NewDataDir(), DataKey = RandomNumberGenerator.GetBytes(32) };
        _store = new ProfileStore(new DataStore(options, NullLogger<DataStore>.Instance));
        _registry = new ProfileRegistry(_store, options, NullLoggerFactory.Instance);
        _restorer = new AccountRestorer(_stub.Auth(), new HostLoginThrottle(), NullLogger.Instance);

        var now = DataStore.Now();
        _store.CreateProfile(
            new ProfileRow(_profileId, now, now, "pub", "priv", null, 0, ProfileCrypto.AccountsKeyCheck(_accountsKey), null, null, null, false),
            new PasskeyRow(ProfileCrypto.NewId(), _profileId, [1], 0, null, null, "w", now, null), []);
    }

    /// <summary>A profile with one saved account, then locked (all sessions gone).</summary>
    private async Task<string> SavedAccountAsync(bool readOnly = true)
    {
        var runtime = _registry.AcquireSession(_profileId);
        Assert.True(runtime.Unlock(_accountsKey, _store.GetProfile(_profileId)!.AccountsKeyCheck));
        var account = ResumeFixtures.NewAccount(_stub.Auth(), refresh: "r1", readOnly: readOnly);
        runtime.Accounts.Add(account, 5, out _);
        Assert.True(runtime.Save(account));
        await runtime.ReleaseSessionAsync();
        Assert.True(account.IsDisposed);
        Assert.Empty(_stub.Logouts);
        return account.Id;
    }

    [Fact]
    public async Task Wrong_key_does_not_unlock()
    {
        await SavedAccountAsync();
        var runtime = _registry.AcquireSession(_profileId);
        Assert.False(runtime.Unlock(RandomNumberGenerator.GetBytes(32), _store.GetProfile(_profileId)!.AccountsKeyCheck));
        Assert.False(runtime.IsUnlocked);
        Assert.Empty(await runtime.RestoreAsync(_restorer, 5, CancellationToken.None));
        Assert.Equal(0, runtime.Accounts.Count);   // nothing it could open
    }

    [Fact]
    public async Task Restore_rotates_and_saves_the_new_token()
    {
        var id = await SavedAccountAsync();

        var runtime = _registry.AcquireSession(_profileId);
        runtime.Unlock(_accountsKey, _store.GetProfile(_profileId)!.AccountsKeyCheck);
        await runtime.RestoreAsync(_restorer, 5, CancellationToken.None);
        var account = Assert.Single(runtime.Accounts.Accounts);
        Assert.Equal(id, account.Id);
        Assert.Equal("r1+", account.TokenData.RefreshToken);
        await runtime.ReleaseSessionAsync();

        // The next unlock presents the rotated token, not the original.
        runtime = _registry.AcquireSession(_profileId);
        runtime.Unlock(_accountsKey, _store.GetProfile(_profileId)!.AccountsKeyCheck);
        await runtime.RestoreAsync(_restorer, 5, CancellationToken.None);
        Assert.Equal(["r1", "r1+"], _stub.Refreshes.Select(r => r.Token));
        await runtime.ReleaseSessionAsync();
    }

    [Fact]
    public async Task Every_refresh_is_saved_inside_the_refresh_lock()
    {
        await SavedAccountAsync();
        var runtime = _registry.AcquireSession(_profileId);
        runtime.Unlock(_accountsKey, _store.GetProfile(_profileId)!.AccountsKeyCheck);
        await runtime.RestoreAsync(_restorer, 5, CancellationToken.None);
        var account = runtime.Accounts.Accounts.Single();

        Assert.True(await account.RefreshTokenAsync());
        await runtime.ReleaseSessionAsync();

        runtime = _registry.AcquireSession(_profileId);
        runtime.Unlock(_accountsKey, _store.GetProfile(_profileId)!.AccountsKeyCheck);
        await runtime.RestoreAsync(_restorer, 5, CancellationToken.None);
        Assert.Equal("r1+++", runtime.Accounts.Accounts.Single().TokenData.RefreshToken);
        await runtime.ReleaseSessionAsync();
    }

    [Fact]
    public async Task Two_sessions_share_one_account()
    {
        await SavedAccountAsync();
        var a = _registry.AcquireSession(_profileId);
        a.Unlock(_accountsKey, _store.GetProfile(_profileId)!.AccountsKeyCheck);
        await a.RestoreAsync(_restorer, 5, CancellationToken.None);

        var b = _registry.AcquireSession(_profileId);
        Assert.Same(a, b);
        await b.RestoreAsync(_restorer, 5, CancellationToken.None);   // nothing new to bring back
        Assert.Single(_stub.Refreshes);

        var one = new Session(a) { Id = "s1" };
        var two = new Session(b) { Id = "s2" };
        Assert.Same(one.Accounts.Single(), two.Accounts.Single());

        await one.DisposeAsync();
        Assert.False(two.Accounts.Single().IsDisposed);   // the other browser keeps working
        await two.DisposeAsync();
        Assert.Equal(0, _registry.Count);
        Assert.Empty(_stub.Logouts);
    }

    [Fact]
    public async Task Delegated_accounts_outlive_the_last_session_for_a_task_and_open_without_the_key()
    {
        var id = await SavedAccountAsync();
        var runtime = _registry.AcquireSession(_profileId);
        runtime.Unlock(_accountsKey, _store.GetProfile(_profileId)!.AccountsKeyCheck);
        await runtime.RestoreAsync(_restorer, 5, CancellationToken.None);
        Assert.True(runtime.SetDelegation(id, true));
        Assert.Equal(ProfileStore.SealServer, _store.Accounts(_profileId).Single().Seal);

        var task = _registry.AcquireTask(_profileId);
        await runtime.ReleaseSessionAsync();          // last browser goes; the task still holds it
        Assert.False(task.IsUnlocked);
        Assert.False(task.Accounts.Accounts.Single().IsDisposed);
        await task.ReleaseTaskAsync();
        Assert.Equal(0, _registry.Count);

        // No browser, no accounts key: the scheduler can still bring it back.
        var later = _registry.AcquireTask(_profileId);
        await later.RestoreAsync(_restorer, 5, CancellationToken.None, new HashSet<string> { id });
        Assert.Equal(id, later.Accounts.Accounts.Single().Id);
        await later.ReleaseTaskAsync();
    }

    [Fact]
    public async Task Profile_sealed_accounts_need_the_key()
    {
        var id = await SavedAccountAsync();
        var task = _registry.AcquireTask(_profileId);
        await task.RestoreAsync(_restorer, 5, CancellationToken.None, new HashSet<string> { id });
        Assert.Equal(0, task.Accounts.Count);
        Assert.Empty(_stub.Refreshes);
        await task.ReleaseTaskAsync();
    }

    [Fact]
    public async Task A_refused_token_marks_the_row_for_a_fresh_sign_in()
    {
        var id = await SavedAccountAsync();
        _stub.RefreshStatus["93.184.215.14"] = HttpStatusCode.BadRequest;

        var runtime = _registry.AcquireSession(_profileId);
        runtime.Unlock(_accountsKey, _store.GetProfile(_profileId)!.AccountsKeyCheck);
        var skipped = await runtime.RestoreAsync(_restorer, 5, CancellationToken.None);

        Assert.Equal("REJECTED", Assert.Single(skipped).Reason);
        Assert.Equal("rejected", _store.Accounts(_profileId).Single().State);
        Assert.Equal("rejected", runtime.Row(id)!.State);
        Assert.NotNull(runtime.RowForLogin(ResumeFixtures.HostA, "alice@example.com"));   // a fresh sign-in reuses it
        await runtime.ReleaseSessionAsync();
    }

    [Fact]
    public async Task Removing_an_account_revokes_and_deletes_it()
    {
        var id = await SavedAccountAsync();
        var runtime = _registry.AcquireSession(_profileId);
        runtime.Unlock(_accountsKey, _store.GetProfile(_profileId)!.AccountsKeyCheck);
        await runtime.RestoreAsync(_restorer, 5, CancellationToken.None);

        Assert.True(await runtime.RemoveAsync(id));
        Assert.Single(_stub.Logouts);
        Assert.Empty(_store.Accounts(_profileId));
        await runtime.ReleaseSessionAsync();
    }
}
