using System.Reflection;
using System.Text;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Server;
using SmarterMailMcp.Core.Models;

namespace SmarterMail.Tests;

/// <summary>
/// <c>docs/tools.md</c> is generated from the tools exactly as the SDK registers them, so the published
/// reference cannot drift from the code. A stale file fails this test; regenerate it with
/// <c>UPDATE_TOOL_DOCS=1 dotnet test tests/SmarterMail.Tests --filter ToolReferenceTests</c>.
/// </summary>
public sealed class ToolReferenceTests
{
    private const string RelativePath = "docs/tools.md";

    private sealed record Section(string Title, string Intro, Assembly Assembly);

    private static readonly Section[] Sections =
    [
        new("Mailbox tools", "Served by **smartermail-mcp-user** and by the agent for mailbox and domain-admin accounts.",
            ToolLibraryTests.Mailbox),
        new("Domain-admin tools", "Served by **smartermail-mcp-user** when the account is a domain admin " +
            "(`SMARTERMAIL_DOMAIN_TOOLS`, default `auto`), and by the agent for domain-admin accounts. " +
            "They act on the signed-in admin's own domain.", ToolLibraryTests.DomainAdmin),
        new("System-admin tools", "Served by **smartermail-mcp-admin** and by the agent for system-admin accounts.",
            ToolLibraryTests.SysAdmin),
    ];

    [Fact]
    public void Tool_reference_is_up_to_date()
    {
        var path = Path.Combine(RepoRoot(), RelativePath);
        var expected = Render();

        if (Environment.GetEnvironmentVariable("UPDATE_TOOL_DOCS") == "1")
        {
            File.WriteAllText(path, expected);
            return;
        }

        Assert.True(File.Exists(path), $"{RelativePath} is missing. Run: UPDATE_TOOL_DOCS=1 dotnet test tests/SmarterMail.Tests --filter ToolReferenceTests");
        var actual = File.ReadAllText(path).ReplaceLineEndings("\n");
        Assert.True(actual == expected,
            $"{RelativePath} is out of date. Run: UPDATE_TOOL_DOCS=1 dotnet test tests/SmarterMail.Tests --filter ToolReferenceTests");
    }

    private static string Render()
    {
        var sb = new StringBuilder();
        sb.Append("<!-- Generated by tests/SmarterMail.Tests/ToolReferenceTests.cs. Do not edit by hand:\n");
        sb.Append("     UPDATE_TOOL_DOCS=1 dotnet test tests/SmarterMail.Tests --filter ToolReferenceTests -->\n\n");
        sb.Append("# Tool reference\n\n");
        sb.Append("Every tool, grouped the way the servers load them. **Read** tools are the only ones a read-only ");
        sb.Append("server lists (`SMARTERMAIL_READ_ONLY`, on by default); **write** tools appear once it is turned off. ");
        sb.Append("**Destructive** writes delete, disable or disconnect something. MCP clients see the same marks as ");
        sb.Append("`readOnlyHint` / `destructiveHint`.\n\n");

        foreach (var section in Sections)
        {
            var groups = ToolsByClass(section.Assembly);
            var total = groups.Sum(g => g.Tools.Count);
            var reads = groups.Sum(g => g.Tools.Count(t => t.ProtocolTool.Annotations?.ReadOnlyHint == true));
            sb.Append($"## {section.Title} ({total}: {reads} read, {total - reads} write)\n\n");
            sb.Append(section.Intro).Append("\n\n");

            foreach (var (category, tools) in groups)
            {
                sb.Append($"### {category}\n\n");
                sb.Append("| Tool | Kind | Description |\n|---|---|---|\n");
                foreach (var tool in tools)
                {
                    var annotations = tool.ProtocolTool.Annotations;
                    var kind = annotations?.ReadOnlyHint == true ? "read"
                        : annotations?.DestructiveHint == true ? "write, destructive"
                        : "write";
                    sb.Append($"| `{tool.ProtocolTool.Name}` | {kind} | {Cell(tool.ProtocolTool.Description)} |\n");
                }
                sb.Append('\n');
            }
        }

        return sb.ToString().TrimEnd('\n') + "\n";
    }

    /// <summary>Tools per <c>[McpServerToolType]</c> class, named by the class ("DomainUserTools" → "Domain user").</summary>
    private static List<(string Category, List<McpServerTool> Tools)> ToolsByClass(Assembly assembly) =>
        assembly.GetTypes()
            .Where(t => t.GetCustomAttribute<McpServerToolTypeAttribute>() is not null)
            .OrderBy(t => t.Name, StringComparer.Ordinal)
            .Select(t => (Category(t), SdkTools(t).OrderBy(x => x.ProtocolTool.Name, StringComparer.Ordinal).ToList()))
            .Where(g => g.Item2.Count > 0)
            .ToList();

    private static List<McpServerTool> SdkTools(Type type)
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddSingleton<UserContext>(_ => throw new InvalidOperationException("placeholder"));
        services.AddSingleton<GlobalContext>(_ => throw new InvalidOperationException("placeholder"));
        services.AddMcpServer().WithTools([type]);
        using var provider = services.BuildServiceProvider();
        return provider.GetServices<McpServerTool>().ToList();
    }

    private static string Category(Type type)
    {
        var name = type.Name.EndsWith("Tools", StringComparison.Ordinal) ? type.Name[..^"Tools".Length] : type.Name;
        var words = new StringBuilder();
        for (var i = 0; i < name.Length; i++)
        {
            if (i > 0 && char.IsUpper(name[i]) && !char.IsUpper(name[i - 1]))
                words.Append(' ');
            words.Append(name[i]);
        }
        return words.ToString();
    }

    private static string Cell(string? text) =>
        (text ?? "").ReplaceLineEndings(" ").Replace("|", "\\|").Trim();

    private static string RepoRoot()
    {
        for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir is not null; dir = dir.Parent)
        {
            if (File.Exists(Path.Combine(dir.FullName, "SmarterMail.slnx")))
                return dir.FullName;
        }
        throw new InvalidOperationException("Repository root (SmarterMail.slnx) not found above " + AppContext.BaseDirectory);
    }
}
